M48
; DRILL file {KiCad (7.0.0)} date Sun Aug  6 02:23:00 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-06T02:23:00-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X0.5555Y-0.1758
X0.7831Y-0.1758
T2
X-0.315Y-0.315
X0.315Y-0.315
T0
M30
